services:
  squirrel-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: squirrel-server
    environment:
      SA_PASSWORD: "P@ssword123!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    networks:
      - squirrel-network
    volumes:
      - mssqldata:/var/opt/mssql
      - ./init-db:/docker-entrypoint-initdb.d
    command: >
      sh -c '/opt/mssql/bin/sqlservr &
      sleep 45 &&
      /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P P@ssword123! -d master -C -i docker-entrypoint-initdb.d/setup.sql;
      echo "Script de inicialização executado!";
      wait;
      '
  squirrel-bot:
    image: skilo600/squirrel-bot:latest
    stdin_open: true
    tty: true 
    container_name: squirrel-bot
    depends_on:
      - squirrel-server
    environment:
      NODE_ENV: development
      DB_CONNECTION_STRING: Server=squirrel-server,1433;Database=squirrelbot;User Id=sa;Password=P@ssword123!;TrustServerCertificate=True;
    ports:
      - "3000:3000"
    networks:
      - squirrel-network
    command: sh -c "sleep 30 && npm start"

networks:
  squirrel-network:
    driver: bridge

volumes:
  mssqldata:
    driver: local
